CREATE TABLE artifacts (id INTEGER PRIMARY KEY, gav TEXT NOT NULL, kind TEXT NOT NULL, sha256 TEXT NOT NULL UNIQUE, path TEXT NOT NULL, size INTEGER, mtime INTEGER, indexed_at INTEGER, has_docs INTEGER DEFAULT 0, has_code_edges INTEGER DEFAULT 0);
CREATE INDEX artifacts_path ON artifacts(path);
CREATE TABLE artifact_paths (path TEXT PRIMARY KEY,artifact_id INTEGER NOT NULL REFERENCES artifacts(id) ON DELETE CASCADE,size INTEGER NOT NULL,mtime INTEGER NOT NULL);
CREATE TABLE source_artifacts (binary_id INTEGER NOT NULL REFERENCES artifacts(id) ON DELETE CASCADE,source_id INTEGER NOT NULL REFERENCES artifacts(id) ON DELETE CASCADE,PRIMARY KEY(binary_id,source_id));
CREATE TABLE symbols (id INTEGER PRIMARY KEY, scip TEXT NOT NULL UNIQUE, artifact_id INTEGER NOT NULL REFERENCES artifacts(id) ON DELETE CASCADE, kind TEXT NOT NULL, name TEXT NOT NULL, owner_id INTEGER, signature TEXT, erased_descriptor TEXT, flags INTEGER, source_file TEXT, line INTEGER, doc TEXT, binary_key TEXT NOT NULL, fqn TEXT, name_path TEXT NOT NULL, class_entry TEXT, parameters TEXT NOT NULL DEFAULT '[]', metadata TEXT NOT NULL DEFAULT '{}', source_start INTEGER DEFAULT -1, source_end INTEGER DEFAULT -1, body_start INTEGER DEFAULT -1, body_end INTEGER DEFAULT -1);
CREATE INDEX symbols_owner ON symbols(owner_id);
CREATE INDEX symbols_owner_member ON symbols(owner_id,name,erased_descriptor);
CREATE INDEX symbols_name ON symbols(name);
CREATE INDEX symbols_fqn ON symbols(fqn);
CREATE INDEX symbols_binary ON symbols(binary_key);
CREATE INDEX symbols_artifact ON symbols(artifact_id);
CREATE INDEX symbols_name_path ON symbols(name_path);
CREATE TABLE edges (src INTEGER NOT NULL, dst INTEGER NOT NULL, kind TEXT NOT NULL, PRIMARY KEY(src,dst,kind)) WITHOUT ROWID;
CREATE INDEX edges_dst ON edges(dst,kind);
CREATE TABLE edge_targets (src INTEGER NOT NULL REFERENCES symbols(id) ON DELETE CASCADE, target TEXT NOT NULL, kind TEXT NOT NULL, PRIMARY KEY(src,target,kind)) WITHOUT ROWID;
CREATE INDEX edge_targets_target ON edge_targets(target);
CREATE TABLE simple_names (simple TEXT NOT NULL, fqn TEXT NOT NULL, artifact_id INTEGER NOT NULL REFERENCES artifacts(id) ON DELETE CASCADE);
CREATE INDEX simple_names_simple ON simple_names(simple);
CREATE INDEX simple_names_artifact ON simple_names(artifact_id);
CREATE TABLE workspace_artifacts (workspace_id TEXT NOT NULL, artifact_id INTEGER NOT NULL REFERENCES artifacts(id) ON DELETE CASCADE, scope TEXT NOT NULL, PRIMARY KEY(workspace_id,artifact_id));
CREATE VIRTUAL TABLE symbols_fts USING fts5(name,doc,content='symbols',content_rowid='id',tokenize='trigram');
CREATE TRIGGER symbols_ai AFTER INSERT ON symbols BEGIN INSERT INTO symbols_fts(rowid,name,doc) VALUES(new.id,new.name,new.doc); END;
CREATE TRIGGER symbols_ad AFTER DELETE ON symbols BEGIN INSERT INTO symbols_fts(symbols_fts,rowid,name,doc) VALUES('delete',old.id,old.name,old.doc); DELETE FROM edges WHERE src=old.id OR dst=old.id; END;
CREATE TRIGGER symbols_au AFTER UPDATE OF name,doc ON symbols BEGIN INSERT INTO symbols_fts(symbols_fts,rowid,name,doc) VALUES('delete',old.id,old.name,old.doc); INSERT INTO symbols_fts(rowid,name,doc) VALUES(new.id,new.name,new.doc); END;
CREATE TABLE counters (name TEXT PRIMARY KEY,value INTEGER NOT NULL);
PRAGMA user_version=1;
