<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>dev.jvmd</groupId><artifactId>jvmd</artifactId><version>0.1.0-SNAPSHOT</version></parent><artifactId>jvmd-lsp</artifactId><dependencies><dependency><groupId>dev.jvmd</groupId><artifactId>jvmd-core</artifactId><version>${project.version}</version></dependency></dependencies></project>
