package dev.jvmd.boot.cold.stage2;

import dev.jvmd.core.hash.Digest;
import dev.jvmd.core.hash.digests.Sha256;
import dev.jvmd.core.tree.ContentTree;
import dev.jvmd.index.layer.local.LocalStore;
import dev.jvmd.index.layer.local.ProcessorRecords;
import dev.jvmd.index.layer.local.ProjectModel;
import dev.jvmd.index.layer.machine.ClassFacts;
import dev.jvmd.index.layer.machine.MachineStore;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.stream.Stream;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;
import javax.tools.ToolProvider;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import static org.assertj.core.api.Assertions.assertThat;

/** Uses an independent, unwrapped javac invocation as the message/position/filtering oracle. */
@Tag("phase-3")
class ProcessorDiagnosticsTest {
    @TempDir Path dir;
    static Stream<Digest> digests() { return Stream.of(Sha256.INSTANCE, new Digests.Sha3()); }
    @AfterAll static void release() { Stage2Support.release(); }
    private static final String INPUT = "package p; @interface Mark { int value(); }\n@Mark(17) public class Input {}\n";

    @ParameterizedTest @MethodSource("digests")
    void reportedMessagesMatchNativeJavacIncludingSuppressionAndErrors(Digest digest) throws Exception {
        var processor = processor();
        var file = source();
        for (var options : List.of(List.<String>of(), List.of("-nowarn"), List.of("-Xmaxwarns", "1"), List.of("-Aerror=true"))) {
            var expected = oracle(processor, file, options);
            try (var host = new ProcessorHost(List.of(processor), List.of(), digest, dir.resolve("wrapped"))) {
                host.sourcePaths(uri -> dir.relativize(Path.of(uri)).toString().replace('\\', '/'));
                try (var compiled = HeaderCompiler.compile(List.of(new HeaderCompiler.Source("m/src/main/java/p/Input.java", file)), List.of(),
                        Stage2Support.JDK, Stage2Support.FEATURE, options, digest, host)) {
                    assertThat(host.diagnostics()).as(options.toString()).isEqualTo(expected);
                    assertThat(ProcessorRecords.Diagnostics.decode(host.diagnostics().encode())).isEqualTo(expected);
                }
            }
        }
    }

    @ParameterizedTest @MethodSource("digests")
    void processorDiagnosticsArePublishedBeforeTheLocalRootAndRefreshedOnEveryRun(Digest digest) throws Exception {
        var processor = processor();
        var file = source();
        var expected = oracle(processor, file, List.of());
        var json = new com.fasterxml.jackson.databind.ObjectMapper();
        var document = (com.fasterxml.jackson.databind.node.ObjectNode) json.readTree(Stage2Support.model(dir, new Stage2Support.Mod("m", "g:m:1", List.of())));
        var processing = ((com.fasterxml.jackson.databind.node.ObjectNode) document.withArray("modules").get(0)).putObject("processing");
        processing.putArray("path").addObject().put("coordinate", "g:processor:1").put("location", processor.toString());
        var model = ProjectModel.parse(json.writeValueAsBytes(document));
        var project = Stage2.projectKey(digest, model);
        var key = LocalStore.processorDiagnosticsKey(project, "m", LocalStore.MAIN);
        var tree = new ContentTree(digest);
        var driver = new Stage2(digest, tree, Stage2Support.FEATURE, 1, dir, ClassFacts::of);
        var first = Stage2Support.jdkOnly(digest).copy();
        var result = driver.run(first, model);
        assertThat(result.faults()).isEmpty();
        assertThat(first.get(key)).isNotNull();
        assertThat(ProcessorRecords.Diagnostics.decode(first.get(key))).isEqualTo(expected);
        var membership = new ArrayList<dev.jvmd.core.tree.Entry>();
        tree.forEach(result.root().hash(), h -> first.get(MachineStore.nodeKey(h)), e -> { if (Arrays.equals(e.key(), key)) membership.add(e); });
        assertThat(membership).hasSize(1);
        assertThat(membership.getFirst().h()).isEqualTo(digest.hash(first.get(key)));
        assertThat(first.readsBeforeRoot()).doesNotContain("PDIAG");

        // Shifting positions changes the run's diagnostics, even if generated bytes and their output root are unchanged.
        Files.writeString(file, "\n" + INPUT);
        var second = first.copy();
        assertThat(driver.run(second, model).faults()).isEmpty();
        var moved = ProcessorRecords.Diagnostics.decode(second.get(key));
        assertThat(moved).isEqualTo(oracle(processor, file, List.of()));
        assertThat(moved).isNotEqualTo(expected);
        assertThat(second.writes(key)).isEqualTo(1);

        processing.putArray("options").add("-Aerror=true");
        var errorModel = ProjectModel.parse(json.writeValueAsBytes(document));
        var errored = second.copy();
        var errorResult = driver.run(errored, errorModel);
        assertThat(errorResult.faults()).anyMatch(f -> f.contains("fixture.Messages") && f.contains("deliberate error"));
        var errorKey = LocalStore.processorDiagnosticsKey(Stage2.projectKey(digest, errorModel), "m", LocalStore.MAIN);
        assertThat(ProcessorRecords.Diagnostics.decode(errored.get(errorKey))).isEqualTo(oracle(processor, file, List.of("-Aerror=true")));

        var repaired = errored.copy();
        assertThat(driver.run(repaired, model).faults()).isEmpty();
        assertThat(ProcessorRecords.Diagnostics.decode(repaired.get(key))).isEqualTo(moved);
    }

    private Path source() throws Exception {
        var file = dir.resolve("m/src/main/java/p/Input.java");
        Files.createDirectories(file.getParent());
        Files.writeString(file, INPUT);
        return file;
    }

    private ProcessorRecords.Diagnostics oracle(Path processor, Path source, List<String> extra) throws Exception {
        var compiler = ToolProvider.getSystemJavaCompiler();
        var messages = new ArrayList<ProcessorRecords.Message>();
        javax.tools.DiagnosticListener<JavaFileObject> diagnostics = d -> {
            // Snapshot the native callback's values before later compiler phases mutate its retained trees.
            if (d.getCode().endsWith(".proc.messager")) messages.add(new ProcessorRecords.Message("fixture.Messages",
                    d.getSource() == null ? null : dir.relativize(Path.of(d.getSource().toUri())).toString().replace('\\', '/'),
                    d.getKind(), d.getPosition(), d.getStartPosition(), d.getEndPosition(), d.getLineNumber(), d.getColumnNumber(), d.getCode(), d.getMessage(Locale.ROOT)));
        };
        var destination = Files.createDirectories(dir.resolve("native"));
        var options = new ArrayList<>(List.of("-proc:full", "--processor-path", processor.toString(), "-classpath", processor.toString(),
                "-encoding", "UTF-8", "-d", destination.toString(), "-s", destination.toString()));
        options.addAll(extra);
        try (var files = compiler.getStandardFileManager(diagnostics, Locale.ROOT, StandardCharsets.UTF_8)) {
            var task = (com.sun.source.util.JavacTask) compiler.getTask(null, files, diagnostics, options, null, files.getJavaFileObjects(source));
            task.setLocale(Locale.ROOT);
            assertThat(task.call()).isEqualTo(!extra.contains("-Aerror=true"));
        }
        if (extra.isEmpty()) assertThat(messages).anyMatch(m -> m.path() == null && m.start() == Diagnostic.NOPOS);
        return new ProcessorRecords.Diagnostics(messages);
    }

    private Path processor() throws Exception {
        var work = dir.resolve("processor");
        var source = """
                package fixture;
                import java.util.*;
                import javax.annotation.processing.*;
                import javax.lang.model.*;
                import javax.lang.model.element.*;
                import javax.tools.Diagnostic.Kind;
                @SupportedAnnotationTypes("p.Mark") @SupportedOptions("error")
                public class Messages extends AbstractProcessor {
                    boolean done;
                    public SourceVersion getSupportedSourceVersion() { return SourceVersion.latestSupported(); }
                    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment round) {
                        if (done || annotations.isEmpty()) return false;
                        done = true;
                        var input = round.getElementsAnnotatedWith(annotations.iterator().next()).iterator().next();
                        var annotation = input.getAnnotationMirrors().get(0);
                        var value = annotation.getElementValues().values().iterator().next();
                        var messages = processingEnv.getMessager();
                        messages.printMessage(Kind.NOTE, "global café");
                        messages.printMessage(Kind.WARNING, "type warning", input);
                        messages.printMessage(Kind.MANDATORY_WARNING, "annotation warning", input, annotation);
                        messages.printMessage(Kind.WARNING, "value warning", input, annotation, value);
                        messages.printMessage(Kind.WARNING, "value warning", input, annotation, value);
                        try (var out = processingEnv.getFiler().createSourceFile("p.Generated", input).openWriter()) {
                            out.write("package p; public class Generated {}");
                        } catch (java.io.IOException e) { throw new RuntimeException(e); }
                        if (processingEnv.getOptions().containsKey("error")) messages.printMessage(Kind.ERROR, "deliberate error", input, annotation, value);
                        return true;
                    }
                }
                """;
        var entries = new java.util.LinkedHashMap<>(Stage2Support.compile(work, Map.of("fixture/Messages.java", source), List.of(), List.of()));
        entries.put("META-INF/services/javax.annotation.processing.Processor", Stage2Support.text("fixture.Messages\n"));
        entries.put("META-INF/gradle/incremental.annotation.processors", Stage2Support.text("fixture.Messages,isolating\n"));
        return Stage2Support.pack(work.resolve("processor.jar"), entries);
    }
}
